### ISSUE TITLE
Cannot create session on any available node

### ISSUE THREAD

**Issue by nekulin** [seleniumkit/gridrouter#39]
`RemoteWebDriver::create( 'http://test:test@ip:4444/wd/hub' )`
Error: Cannot create session on any available node

**Comment by smecsia** [comment]
@nekulin Please provide the contents of `/etc/grid-router/quota/*.xml` files and also the contents of the logs `/var/log/grid-router/*.log`.

**Comment by vania-pooh** [comment]
This error means that GridRouter tried all hosts from XML files and didn't succeed to create a session on each host. Possible reasons:
1) Missing file **/etc/grid-router/quota/test.xml**
2) Wrong hosts or ports in this file

**Comment by nekulin** [comment]
/etc/grid-router/quota/test.xml describes the regions and the version I specify myself ? The file exists /etc/grid-router/quota/test.xml but I tried instead to specify host server Ip with different ports, but it doesn't work

**Comment by vania-pooh** [comment]
Need more details about XML files and your capabilities.

**Comment by nekulin** [comment]
Errors
`
2016-12-21 20:04:15,426 [3589513-14] INFO  RouteServlet         - [SESSION_ATTEMPTED] [test] [94.25.586.71] [firefox] [http://my-firefox33-host-1.example.com:4444] [1]
2016-12-21 20:04:15,706 [3589513-14] ERROR RouteServlet         - [HUB_COMMUNICATION_FAILURE] [test] [94.25.586.71] [firefox] - http://my-firefox33-host-1.example.com:4444
2016-12-21 20:04:15,707 [3589513-14] INFO  RouteServlet         - [SESSION_ATTEMPTED] [test] [94.25.586.71] [firefox] [http://my-firefox33-host-2.example.com:4444] [2]
`
Test XML
`<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
    <browser name="firefox" defaultVersion="33.0">
        <version number="33.0">
            <region name="us-west">
                <host port="4444" count="5"/>
            </region>
            <region name="us-east">
                <host port="4445" count="5"/>
            </region>
        </version>
        <version number="38.0">
            <region name="us-west">
                <host port="4446" count="4"/>
                <host port="4447" count="4"/>
            </region>
            <region name="us-east">
                <host port="4448" count="4"/>
            </region>
        </version>
    </browser>
</qa:browsers>
`


http://138.197.42.211:4444/ Unable to connect

**Comment by nekulin** [comment]
Ubuntu 14
`
ERROR: Context 'file:///usr/share/grid-router/grid-router-deb.war' does not exist
`

**Comment by innokenty** [comment]
That means the configuration is fine and your request is properly proxied to that host, but the hub responds with a failure. Maybe it doesn't even exist? Try to run your tests against `my-firefox33-host-1.example.com:4444` instead of running against GridRouter.

**Comment by vania-pooh** [comment]
This was an example host. You should use real host names:
```
vania-pooh:~$ host my-firefox33-host-1.example.com
Host my-firefox33-host-1.example.com not found: 3(NXDOMAIN)
```

**Comment by nekulin** [comment]
There is no domain, why not use a non-domain to ip + port ?

**Comment by vania-pooh** [comment]
In that case you at least need to specify this IP in XML.

**Comment by nekulin** [comment]
I tried not working as it is now when I point the host comes to the page http://138.197.42.211:4444/ with error 404 and 403

**Comment by nekulin** [comment]
No ready docker ? grid console is there ?

**Comment by vania-pooh** [comment]
This is not a Selenium Hub reimplementation! It just proxies requests to real Selenium hubs. You still need to use original Selenium to serve requests. Thus there's no console.
