### ISSUE TITLE
Jetty 403 forbidden

### ISSUE THREAD

**Issue by tizzythegrey** [seleniumkit/gridrouter#41]
I am trying to test this but when i browse to the web app it gives me 

HTTP ERROR 403

Problem accessing /. Reason:

    Forbidden
Powered by Jetty:// 9.3.3.v20150827

Any suggestion? Thanks for any help here.

**Comment by vania-pooh** [comment]
@tizzythegrey which webapp are you speaking about? There's no web-interface in GridRouter like Selenium Hub Console.

**Comment by tizzythegrey** [comment]
Thank you for the response. Ok (1) how do I test that GridRouter can talk to both of my selenium hubs? (2) do I need to actually create the user in user.properties on the OS level?

Setup:
2 hubs with nodes attached to each hub. 
Grid router node in the same network with hubs. hubs address is in the quota.xml and user.properties has a test user.

**Comment by tizzythegrey** [comment]
To answer your question @Ivan, I was under the impression that I can browse to the jetty server with http://user:pass@gridrouter-server:4444 but doing that gives the error message above. I basically want to know how to test the connection from gridrouter to hubs

**Comment by ivan** [comment]
@ivan sends the wrong Ivan an email

**Comment by smecsia** [comment]
@tizzythegrey The best way to debug the connection is to watch the log files. There you can find the full information regarding each session request. 
As stated by @vania-pooh, unlike Selenium Hub Gridrouter does not have any web UI, but you may consider to use [Selenograph](https://github.com/seleniumkit/selenograph) if you need it.

**Comment by innokenty** [comment]
@tizzythegrey to test the GridRouter try to launch an instance of Selenium's `RemoteWebDriver` against the address you provided. Instead of giving the address of a hub just give it this address. And then watch the logs or see what Selenium error message will be.

**Comment by innokenty** [comment]
As already stated, there's no web-interface whatsoever, so the only way to tests it either the one described above, or requesting a browser manually from console with `curl` command.

**Comment by vania-pooh** [comment]
@tizzythegrey no need to create system users, just use login and password from users.properties file. To test simply launch your test like you do with standard Selenium Hub against the URL:
```
 http://user:pass@gridrouter-server:4444/wd/hub
```
Log file is usually located at:```/var/log/grid-router/grid-router.log```

**Comment by tizzythegrey** [comment]
Perfect. Thanks to all of you guys and forgive me if the question was stupid. I appreciate the quick response.
