### ISSUE TITLE
Installation on ubuntu 17.10

### ISSUE THREAD

**Issue by ghost** [seleniumkit/gridrouter#43]
I'm getting the following error after running apt-get update:

`The repository 'http://ppa.launchpad.net/yandex-qatools/gridrouter/ubuntu artful Release' does not have a Release file.`

I've also tried cloning the gridrouter-deb-master repository and building from that but I'm stuck on the following error:

`Now signing changes and any dsc files...
 signfile dsc yandex-grid-router_1.27-1.dsc Ivan Krutov <vania-pooh@yandex-team.ru>
gpg: skipped "Ivan Krutov <vania-pooh@yandex-team.ru>": No secret key
gpg: /tmp/debsign.eCi108TX/yandex-grid-router_1.27-1.dsc: clearsign failed: No secret key`

**Comment by vania-pooh** [comment]
@eventjumbler unfortunately this project was abandoned in favor to this one: https://github.com/aerokube/ggr which has fully compatible XML configuration files.
